[2025-08-14T22:34:49.371+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-14T22:34:49.389+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mini_GCP.export_duckdb_to_postgres manual__2025-08-14T22:29:35.650965+00:00 [queued]>
[2025-08-14T22:34:49.394+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mini_GCP.export_duckdb_to_postgres manual__2025-08-14T22:29:35.650965+00:00 [queued]>
[2025-08-14T22:34:49.394+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-14T22:34:49.401+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): export_duckdb_to_postgres> on 2025-08-14 22:29:35.650965+00:00
[2025-08-14T22:34:49.409+0000] {standard_task_runner.py:63} INFO - Started process 368 to run task
[2025-08-14T22:34:49.411+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mini_GCP', 'export_duckdb_to_postgres', 'manual__2025-08-14T22:29:35.650965+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpgv1jci_z']
[2025-08-14T22:34:49.413+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask export_duckdb_to_postgres
[2025-08-14T22:34:49.447+0000] {task_command.py:426} INFO - Running <TaskInstance: Mini_GCP.export_duckdb_to_postgres manual__2025-08-14T22:29:35.650965+00:00 [running]> on host 13aade4e0d1e
[2025-08-14T22:34:49.499+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='CamilaJaviera' AIRFLOW_CTX_DAG_ID='Mini_GCP' AIRFLOW_CTX_TASK_ID='export_duckdb_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T22:29:35.650965+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T22:29:35.650965+00:00'
[2025-08-14T22:34:49.500+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-14T22:34:49.521+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-14T22:34:49.522+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/../export/export_to_postgres.py", line 27, in export_to_postgres
    engine = create_engine(f"postgresql+psycopg2://{PG_USER}:{PG_PASSWORD}@{PG_HOST}:{PG_PORT}/{PG_DB}")
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 514, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 738, in make_url
    return _parse_url(name_or_url)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/url.py", line 794, in _parse_url
    components["port"] = int(components["port"])
ValueError: invalid literal for int() with base 10: 'None'
[2025-08-14T22:34:49.529+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Mini_GCP, task_id=export_duckdb_to_postgres, run_id=manual__2025-08-14T22:29:35.650965+00:00, execution_date=20250814T222935, start_date=20250814T223449, end_date=20250814T223449
[2025-08-14T22:34:49.536+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task export_duckdb_to_postgres (invalid literal for int() with base 10: 'None'; 368)
[2025-08-14T22:34:49.583+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-14T22:34:49.601+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T22:34:49.603+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
