[2025-08-14T22:49:12.555+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-14T22:49:12.576+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mini_GCP.export_duckdb_to_postgres manual__2025-08-14T22:49:01.329849+00:00 [queued]>
[2025-08-14T22:49:12.580+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mini_GCP.export_duckdb_to_postgres manual__2025-08-14T22:49:01.329849+00:00 [queued]>
[2025-08-14T22:49:12.580+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-14T22:49:12.588+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): export_duckdb_to_postgres> on 2025-08-14 22:49:01.329849+00:00
[2025-08-14T22:49:12.597+0000] {standard_task_runner.py:63} INFO - Started process 227 to run task
[2025-08-14T22:49:12.599+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Mini_GCP', 'export_duckdb_to_postgres', 'manual__2025-08-14T22:49:01.329849+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpxhse7xm7']
[2025-08-14T22:49:12.601+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask export_duckdb_to_postgres
[2025-08-14T22:49:12.637+0000] {task_command.py:426} INFO - Running <TaskInstance: Mini_GCP.export_duckdb_to_postgres manual__2025-08-14T22:49:01.329849+00:00 [running]> on host 89eaeffba76c
[2025-08-14T22:49:12.690+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='CamilaJaviera' AIRFLOW_CTX_DAG_ID='Mini_GCP' AIRFLOW_CTX_TASK_ID='export_duckdb_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-08-14T22:49:01.329849+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-14T22:49:01.329849+00:00'
[2025-08-14T22:49:12.691+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-14T22:49:12.706+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-14T22:49:12.706+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/../export/export_to_postgres.py", line 23, in export_to_postgres
    con = duckdb.connect("data/warehouse/sales.duckdb")
duckdb.duckdb.IOException: IO Error: Cannot open file "/opt/airflow/data/warehouse/sales.duckdb": No such file or directory
[2025-08-14T22:49:12.714+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Mini_GCP, task_id=export_duckdb_to_postgres, run_id=manual__2025-08-14T22:49:01.329849+00:00, execution_date=20250814T224901, start_date=20250814T224912, end_date=20250814T224912
[2025-08-14T22:49:12.721+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task export_duckdb_to_postgres (IO Error: Cannot open file "/opt/airflow/data/warehouse/sales.duckdb": No such file or directory; 227)
[2025-08-14T22:49:12.771+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-14T22:49:12.789+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-14T22:49:12.791+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
